l2:
  chain-configs:
    rollup-a:
      # Private key (without 0x prefix) for a funded account
      pk: 0000000000000000000000000000000000000000000000000000000000000000
      # Chain ID
      id: 77777
      # JSON-RPC
      rpc-url: http://localhost:18545

    rollup-b:
      # Private key (without 0x prefix) for a funded account
      pk: 0000000000000000000000000000000000000000000000000000000000000000
      # Chain ID
      id: 88888
      # JSON-RPC
      rpc-url: http://localhost:28545

  # Smart contracts deployed to both rollups
  # These are typically deployed at the same address on both chains
  # which is why this section is shared rather than duplicated per rollup
  contracts:
      bridge:
        address: 0x
        abi: ''
      ping-pong: 
        address: 0x
        abi: ''
      token:
        address: 0x
        abi: ''
